name: OpenSSF Scorecard

on:
  branch_protection_rule:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "29 4 * * 1"
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  analysis:
    name: scorecard-analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
        with:
          publish_results: true
          results_file: results.sarif
          results_format: sarif

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          if-no-files-found: error
          name: openssf-scorecard-results
          path: results.sarif

      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@ebcb5b36ded6beda4ceefea6a8bc4cc885255bb3
        with:
          sarif_file: results.sarif
