name: Secret Scan

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '11 4 * * 1'

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@dcedce43c6f43de0b836d1fe38946645c9c638dc
        with:
          args: detect --source . --no-banner --redact --config .gitleaks.toml
